<?php

return [
	'format' => [
		'3d' => __( '3D', 'wpmovielibrary' ),
		'sd' => __( 'SD', 'wpmovielibrary' ),
		'hd' => __( 'HD', 'wpmovielibrary' ),
	],
	'language' => [
		'ar' => __( 'Arabic', 'wpmovielibrary-iso' ),
		'bg' => __( 'Bulgarian', 'wpmovielibrary-iso' ),
		'cs' => __( 'Czech', 'wpmovielibrary-iso' ),
		'cn' => __( 'Cantonese', 'wpmovielibrary-iso' ),
		'da' => __( 'Danish', 'wpmovielibrary-iso' ),
		'de' => __( 'German', 'wpmovielibrary-iso' ),
		'el' => __( 'Greek', 'wpmovielibrary-iso' ),
		'en' => __( 'English', 'wpmovielibrary-iso' ),
		'es' => __( 'Spanish', 'wpmovielibrary-iso' ),
		'fa' => __( 'Farsi', 'wpmovielibrary-iso' ),
		'fi' => __( 'Finnish', 'wpmovielibrary-iso' ),
		'fr' => __( 'French', 'wpmovielibrary-iso' ),
		'he' => __( 'Hebrew', 'wpmovielibrary-iso' ),
		'hi' => __( 'Hindi', 'wpmovielibrary-iso' ),
		'hu' => __( 'Hungarian', 'wpmovielibrary-iso' ),
		'it' => __( 'Italian', 'wpmovielibrary-iso' ),
		'ja' => __( 'Japanese', 'wpmovielibrary-iso' ),
		'ko' => __( 'Korean', 'wpmovielibrary-iso' ),
		'nl' => __( 'Dutch', 'wpmovielibrary-iso' ),
		'no' => __( 'Norwegian', 'wpmovielibrary-iso' ),
		'pl' => __( 'Polish', 'wpmovielibrary-iso' ),
		'pt' => __( 'Portuguese', 'wpmovielibrary-iso' ),
		'ru' => __( 'Russian', 'wpmovielibrary-iso' ),
		'sv' => __( 'Swedish', 'wpmovielibrary-iso' ),
		'tr' => __( 'Turkish', 'wpmovielibrary-iso' ),
		'uk' => __( 'Ukrainian', 'wpmovielibrary-iso' ),
		'zh' => __( 'Mandarin', 'wpmovielibrary-iso' ),
	],
	'media' => [
		'dvd'     => __( 'DVD', 'wpmovielibrary' ),
		'bluray'  => __( 'Blu-ray', 'wpmovielibrary' ),
		'vod'     => __( 'VoD', 'wpmovielibrary' ),
		'divx'    => __( 'DivX', 'wpmovielibrary' ),
		'vhs'     => __( 'VHS', 'wpmovielibrary' ),
		'cinema'  => __( 'Cinema', 'wpmovielibrary' ),
		'other'   => __( 'Other', 'wpmovielibrary' ),
	],
	'rating' => [
		'0.0' => __( 'Not rated', 'wpmovielibrary' ),
		'0.5' => __( 'Junk', 'wpmovielibrary' ),
		'1.0' => __( 'Very bad', 'wpmovielibrary' ),
		'1.5' => __( 'Bad', 'wpmovielibrary' ),
		'2.0' => __( 'Not that bad', 'wpmovielibrary' ),
		'2.5' => __( 'Average', 'wpmovielibrary' ),
		'3.0' => __( 'Not bad', 'wpmovielibrary' ),
		'3.5' => __( 'Good', 'wpmovielibrary' ),
		'4.0' => __( 'Very good', 'wpmovielibrary' ),
		'4.5' => __( 'Excellent', 'wpmovielibrary' ),
		'5.0' => __( 'Masterpiece', 'wpmovielibrary' ),
	],
	'status' => [
		'available'   => __( 'Available', 'wpmovielibrary' ),
		'loaned'	  => __( 'Loaned', 'wpmovielibrary' ),
		'scheduled'   => __( 'Scheduled', 'wpmovielibrary' ),
		'unavailable' => __( 'Unavailable', 'wpmovielibrary' ),
	],
	'subtitles' => [
		'none' => __( 'None', 'wpmovielibrary' ),
		'ar' => __( 'Arabic', 'wpmovielibrary-iso' ),
		'bg' => __( 'Bulgarian', 'wpmovielibrary-iso' ),
		'cs' => __( 'Czech', 'wpmovielibrary-iso' ),
		'cn' => __( 'Cantonese', 'wpmovielibrary-iso' ),
		'da' => __( 'Danish', 'wpmovielibrary-iso' ),
		'de' => __( 'German', 'wpmovielibrary-iso' ),
		'el' => __( 'Greek', 'wpmovielibrary-iso' ),
		'en' => __( 'English', 'wpmovielibrary-iso' ),
		'es' => __( 'Spanish', 'wpmovielibrary-iso' ),
		'fa' => __( 'Farsi', 'wpmovielibrary-iso' ),
		'fi' => __( 'Finnish', 'wpmovielibrary-iso' ),
		'fr' => __( 'French', 'wpmovielibrary-iso' ),
		'he' => __( 'Hebrew', 'wpmovielibrary-iso' ),
		'hi' => __( 'Hindi', 'wpmovielibrary-iso' ),
		'hu' => __( 'Hungarian', 'wpmovielibrary-iso' ),
		'it' => __( 'Italian', 'wpmovielibrary-iso' ),
		'ja' => __( 'Japanese', 'wpmovielibrary-iso' ),
		'ko' => __( 'Korean', 'wpmovielibrary-iso' ),
		'nl' => __( 'Dutch', 'wpmovielibrary-iso' ),
		'no' => __( 'Norwegian', 'wpmovielibrary-iso' ),
		'pl' => __( 'Polish', 'wpmovielibrary-iso' ),
		'pt' => __( 'Portuguese', 'wpmovielibrary-iso' ),
		'ru' => __( 'Russian', 'wpmovielibrary-iso' ),
		'sv' => __( 'Swedish', 'wpmovielibrary-iso' ),
		'tr' => __( 'Turkish', 'wpmovielibrary-iso' ),
		'uk' => __( 'Ukrainian', 'wpmovielibrary-iso' ),
		'zh' => __( 'Mandarin', 'wpmovielibrary-iso' ),
	],
];