<?php

return [
    'movie' => [
        'labels' => [
        'name'                     => _x( 'Movies', 'movie general name', 'watchrd' ),
        'singular_name'            => _x( 'Movie', 'movie singular name', 'watchrd' ),
        'add_new'                  => _x( 'Add New', 'movie', 'watchrd' ),
        'add_new_item'             => __( 'Add New Movie', 'watchrd' ),
        'edit_item'                => __( 'Edit Movie', 'watchrd' ),
        'new_item'                 => __( 'New Movie', 'watchrd' ),
        'view_item'                => __( 'View Movie', 'watchrd' ),
        'view_items'               => __( 'View Movies', 'watchrd' ),
        'search_items'             => __( 'Search Movies', 'watchrd' ),
        'not_found'                => __( 'No movies found.', 'watchrd' ),
        'not_found_in_trash'       => __( 'No movies found in Trash.', 'watchrd' ),
        'all_items'                => __( 'All Movies', 'watchrd' ),
        'archives'                 => __( 'Movie Archives', 'watchrd' ),
        'attributes'               => __( 'Movie Attributes', 'watchrd' ),
        'insert_into_item'         => __( 'Insert into movie', 'watchrd' ),
        'uploaded_to_this_item'    => __( 'Uploaded to this movie', 'watchrd' ),
        'featured_image'           => _x( 'Featured image', 'movie', 'watchrd' ),
        'set_featured_image'       => _x( 'Set featured image', 'movie', 'watchrd' ),
        'remove_featured_image'    => _x( 'Remove featured image', 'movie', 'watchrd' ),
        'use_featured_image'       => _x( 'Use as featured image', 'movie', 'watchrd' ),
        'filter_items_list'        => __( 'Filter movies list', 'watchrd' ),
        'filter_by_date'           => __( 'Filter by date', 'watchrd' ),
        'items_list_navigation'    => __( 'Movies list navigation', 'watchrd' ),
        'items_list'               => __( 'Movies list', 'watchrd' ),
        'item_published'           => __( 'Movie published.', 'watchrd' ),
        'item_published_privately' => __( 'Movie published privately.', 'watchrd' ),
        'item_reverted_to_draft'   => __( 'Movie reverted to draft.', 'watchrd' ),
        'item_scheduled'           => __( 'Movie scheduled.', 'watchrd' ),
        'item_updated'             => __( 'Movie updated.', 'watchrd' ),
        ],
        'description'           => '',
        'public'                => true,
        'hierarchical'          => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'show_ui'               => true,
        'show_in_menu'          => 'watchrd',
        'show_in_nav_menus'     => true,
        'show_in_admin_bar'     => true,
        'supports'              => [ 'title', 'editor', 'excerpt', 'thumbnail', 'custom-fields', 'comments', 'revisions', 'author' ],
        'register_meta_box_cb'  => null,
        'taxonomies'            => [ 'actor', 'collection', 'genre' ],
        'has_archive'           => true,
        'rewrite'               => [
        'slug' => _x( 'movies', 'movie rewrite slug', 'watchrd' ),
        ],
        'query_var'             => true,
        'can_export'            => true,
        'delete_with_user'      => false,
        'show_in_rest'          => true,
        'rest_base'             => 'movies',
    ],
];