<?php

return [
	'movie' => [
		'labels' => [
			'name'                     => _x( 'Movies', 'movie general name', 'wpmovielibrary' ),
			'singular_name'            => _x( 'Movie', 'movie singular name', 'wpmovielibrary' ),
			'add_new'                  => _x( 'Add New', 'movie', 'wpmovielibrary' ),
			'add_new_item'             => __( 'Add New Movie', 'wpmovielibrary' ),
			'edit_item'                => __( 'Edit Movie', 'wpmovielibrary' ),
			'new_item'                 => __( 'New Movie', 'wpmovielibrary' ),
			'view_item'                => __( 'View Movie', 'wpmovielibrary' ),
			'view_items'               => __( 'View Movies', 'wpmovielibrary' ),
			'search_items'             => __( 'Search Movies', 'wpmovielibrary' ),
			'not_found'                => __( 'No movies found.', 'wpmovielibrary' ),
			'not_found_in_trash'       => __( 'No movies found in Trash.', 'wpmovielibrary' ),
			'all_items'                => __( 'All Movies', 'wpmovielibrary' ),
			'archives'                 => __( 'Movie Archives', 'wpmovielibrary' ),
			'attributes'               => __( 'Movie Attributes', 'wpmovielibrary' ),
			'insert_into_item'         => __( 'Insert into movie', 'wpmovielibrary' ),
			'uploaded_to_this_item'    => __( 'Uploaded to this movie', 'wpmovielibrary' ),
			'featured_image'           => _x( 'Featured image', 'movie', 'wpmovielibrary' ),
			'set_featured_image'       => _x( 'Set featured image', 'movie', 'wpmovielibrary' ),
			'remove_featured_image'    => _x( 'Remove featured image', 'movie', 'wpmovielibrary' ),
			'use_featured_image'       => _x( 'Use as featured image', 'movie', 'wpmovielibrary' ),
			'filter_items_list'        => __( 'Filter movies list', 'wpmovielibrary' ),
			'filter_by_date'           => __( 'Filter by date', 'wpmovielibrary' ),
			'items_list_navigation'    => __( 'Movies list navigation', 'wpmovielibrary' ),
			'items_list'               => __( 'Movies list', 'wpmovielibrary' ),
			'item_published'           => __( 'Movie published.', 'wpmovielibrary' ),
			'item_published_privately' => __( 'Movie published privately.', 'wpmovielibrary' ),
			'item_reverted_to_draft'   => __( 'Movie reverted to draft.', 'wpmovielibrary' ),
			'item_scheduled'           => __( 'Movie scheduled.', 'wpmovielibrary' ),
			'item_updated'             => __( 'Movie updated.', 'wpmovielibrary' ),
		],
		'description'           => '',
		'public'                => true,
		'hierarchical'          => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'show_ui'               => true,
		'show_in_menu'          => 'wpmovielibrary',
		'show_in_nav_menus'     => true,
		'show_in_admin_bar'     => true,
		'supports'              => [ 'title', 'editor', 'excerpt', 'thumbnail', 'custom-fields', 'comments', 'revisions', 'author' ],
		'register_meta_box_cb'  => null,
		'taxonomies'            => [ 'wpmoly_movie_actor', 'wpmoly_movie_collection', 'wpmoly_movie_genre' ],
		'has_archive'           => true,
		'rewrite'               => [
			'slug' => _x( 'movies', 'movie rewrite slug', 'wpmovielibrary' ),
		],
		'query_var'             => true,
		'can_export'            => true,
		'delete_with_user'      => false,
		'show_in_rest'          => true,
		'rest_base'             => 'movies',
	],
];