<?php

return [
	'movie' => [
		'crew' => [
			// director, first_assistant_director, second_assistant_director,
			// producer, executive_producer, associate_producer,
			// screenplay, writer, novel,
			// original_music_composer, music, music_editor,
			// director_of_photography, second_unit_director_of_photography,
			// chief_lighting_technician, gaffer,
			// editor, casting, stunt_coordinator,
			// sound_designer, sound_editor
			'director' => [], // use actor taxonomy as reference for args
		],
		'details' => [
			'format' => [], // use actor taxonomy as reference for args
			'language' => [], // use actor taxonomy as reference for args
			'media' => [], // use actor taxonomy as reference for args
			'rating' => [], // use actor taxonomy as reference for args
			'status' => [], // use actor taxonomy as reference for args
			'subtitles' => [], // use actor taxonomy as reference for args
		],
		'general' => [
			'actor' => [
				'labels' => [
					'name'                       => _x( 'Actors', 'taxonomy general name', 'wpmovielibrary' ),
					'singular_name'              => _x( 'Actor', 'taxonomy singular name', 'wpmovielibrary' ),
					'search_items'               => __( 'Search Actors', 'wpmovielibrary' ),
					'popular_items'              => __( 'Popular Actors', 'wpmovielibrary' ),
					'all_items'                  => __( 'All Actors', 'wpmovielibrary' ),
					'edit_item'                  => __( 'Edit Actor', 'wpmovielibrary' ),
					'view_item'                  => __( 'View Actor', 'wpmovielibrary' ),
					'update_item'                => __( 'Update Actor', 'wpmovielibrary' ),
					'add_new_item'               => __( 'Add New Actor', 'wpmovielibrary' ),
					'new_item_name'              => __( 'New Actor Name', 'wpmovielibrary' ),
					'separate_items_with_commas' => __( 'Separate actors with commas', 'wpmovielibrary' ),
					'add_or_remove_items'        => __( 'Add or remove actors', 'wpmovielibrary' ),
					'choose_from_most_used'      => __( 'Choose from the most used actors', 'wpmovielibrary' ),
					'not_found'                  => __( 'No actors found.', 'wpmovielibrary' ),
					'no_terms'                   => __( 'No actors', 'wpmovielibrary' ),
					'items_list_navigation'      => __( 'Actors list navigation', 'wpmovielibrary' ),
					'items_list'                 => __( 'Actors list', 'wpmovielibrary' ),
					'most_used'                  => _x( 'Most Used', 'actors', 'wpmovielibrary' ),
					'back_to_items'              => __( '&larr; Go to Actors', 'wpmovielibrary' ),
				],
				'description'        => '',
				'public'             => true,
				'publicly_queryable' => true,
				'hierarchical'       => false,
				'sort'               => true,
				'show_ui'            => true,
				'show_in_menu'       => true,
				'show_in_nav_menus'  => true,
				'show_in_rest'       => true,
				'show_in_quick_edit' => true,
				'show_admin_column'  => true,
				'rewrite'            => [
					'slug' => _x( 'actors', 'actor taxonomy slug', 'wpmovielibrary' ),
				],
			],
			'collection' => [
				'labels' => [
					'name'                       => _x( 'Collections', 'taxonomy general name', 'wpmovielibrary' ),
					'singular_name'              => _x( 'Collection', 'taxonomy singular name', 'wpmovielibrary' ),
					'search_items'               => __( 'Search Collections', 'wpmovielibrary' ),
					'popular_items'              => __( 'Popular Collections', 'wpmovielibrary' ),
					'all_items'                  => __( 'All Collections', 'wpmovielibrary' ),
					'edit_item'                  => __( 'Edit Collection', 'wpmovielibrary' ),
					'view_item'                  => __( 'View Collection', 'wpmovielibrary' ),
					'update_item'                => __( 'Update Collection', 'wpmovielibrary' ),
					'add_new_item'               => __( 'Add New Collection', 'wpmovielibrary' ),
					'new_item_name'              => __( 'New Collection Name', 'wpmovielibrary' ),
					'separate_items_with_commas' => __( 'Separate collections with commas', 'wpmovielibrary' ),
					'add_or_remove_items'        => __( 'Add or remove collections', 'wpmovielibrary' ),
					'choose_from_most_used'      => __( 'Choose from the most used collections', 'wpmovielibrary' ),
					'not_found'                  => __( 'No collections found.', 'wpmovielibrary' ),
					'no_terms'                   => __( 'No collections', 'wpmovielibrary' ),
					'items_list_navigation'      => __( 'Collections list navigation', 'wpmovielibrary' ),
					'items_list'                 => __( 'Collections list', 'wpmovielibrary' ),
					'most_used'                  => _x( 'Most Used', 'collections', 'wpmovielibrary' ),
					'back_to_items'              => __( '&larr; Go to Collections', 'wpmovielibrary' ),
				],
				'description'        => '',
				'public'             => true,
				'publicly_queryable' => true,
				'hierarchical'       => true,
				'sort'               => true,
				'show_ui'            => true,
				'show_in_menu'       => true,
				'show_in_nav_menus'  => true,
				'show_in_rest'       => true,
				'show_in_quick_edit' => true,
				'show_admin_column'  => true,
				'rewrite'            => [
					'slug' => _x( 'collections', 'collection taxonomy slug', 'wpmovielibrary' ),
				],
			],
			'genre' => [
				'labels' => [
					'name'                       => _x( 'Genres', 'taxonomy general name', 'wpmovielibrary' ),
					'singular_name'              => _x( 'Genre', 'taxonomy singular name', 'wpmovielibrary' ),
					'search_items'               => __( 'Search Genres', 'wpmovielibrary' ),
					'popular_items'              => __( 'Popular Genres', 'wpmovielibrary' ),
					'all_items'                  => __( 'All Genres', 'wpmovielibrary' ),
					'edit_item'                  => __( 'Edit Genre', 'wpmovielibrary' ),
					'view_item'                  => __( 'View Genre', 'wpmovielibrary' ),
					'update_item'                => __( 'Update Genre', 'wpmovielibrary' ),
					'add_new_item'               => __( 'Add New Genre', 'wpmovielibrary' ),
					'new_item_name'              => __( 'New Genre Name', 'wpmovielibrary' ),
					'separate_items_with_commas' => __( 'Separate genres with commas', 'wpmovielibrary' ),
					'add_or_remove_items'        => __( 'Add or remove genres', 'wpmovielibrary' ),
					'choose_from_most_used'      => __( 'Choose from the most used genres', 'wpmovielibrary' ),
					'not_found'                  => __( 'No genres found.', 'wpmovielibrary' ),
					'no_terms'                   => __( 'No genres', 'wpmovielibrary' ),
					'items_list_navigation'      => __( 'Genres list navigation', 'wpmovielibrary' ),
					'items_list'                 => __( 'Genres list', 'wpmovielibrary' ),
					'most_used'                  => _x( 'Most Used', 'genres', 'wpmovielibrary' ),
					'back_to_items'              => __( '&larr; Go to Genres', 'wpmovielibrary' ),
				],
				'description'        => '',
				'public'             => true,
				'publicly_queryable' => true,
				'hierarchical'       => false,
				'sort'               => true,
				'show_ui'            => true,
				'show_in_menu'       => true,
				'show_in_nav_menus'  => true,
				'show_in_rest'       => true,
				'show_in_quick_edit' => true,
				'show_admin_column'  => true,
				'rewrite'            => [
					'slug' => _x( 'genres', 'genre taxonomy slug', 'wpmovielibrary' ),
				],
			],
		],
		'technical' => [
			// original_language, origin_country,
			// spoken_language, production_country, production_company
		],
	],
];